### ISSUE TITLE
No upload speed

### ISSUE THREAD

**Issue by bartlenaerts** [speedchecker/react_plugin#6]
Hi,

I'm using Speedchecker in my React Native application to show download and upload speed. Download is working perfectly, but the upload speed is always 0. What am I doing wrong? Anybody already had this issue?

![IMG_0944](https://github.com/speedchecker/react_plugin/assets/657416/f08cf0da-af13-4190-8c69-36971d6a4a8b)
![IMG_0945](https://github.com/speedchecker/react_plugin/assets/657416/1d39ae8a-968c-487e-8a06-be384c20aa62)

It is not that I have a problem with my network, because the SpeedChecker app works like a charm.

![IMG_0947](https://github.com/speedchecker/react_plugin/assets/657416/aa649c1b-eab3-4bd8-8b62-aad9f18f3de5)

Thanks for the help!

**Comment by Florent75** [comment]
Hi Bart,
Could you share your code to make it work ? 
I am not succeeding in getting back network data after calling the startTest function

**Comment by Marcuspo** [comment]
+1
has upload speed but not continue the function
